/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppearanceSettings {
  'heroImage' : [] | [ExternalBlob],
  'shopBackground' : [] | [ExternalBlob],
  'homepageBackground' : [] | [ExternalBlob],
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface GCashSettings {
  'merchantName' : string,
  'qrCodeImage' : [] | [ExternalBlob],
  'accountNumber' : string,
}
export interface Order {
  'id' : string,
  'isGuestOrder' : boolean,
  'status' : OrderStatus,
  'paymentMethod' : string,
  'userId' : [] | [Principal],
  'createdAt' : bigint,
  'guestEmail' : [] | [string],
  'shippingAddress' : string,
  'totalPhpCents' : bigint,
  'items' : Array<
    { 'productId' : string, 'pricePhpCents' : bigint, 'quantity' : bigint }
  >,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'returned' : null };
export interface ProductMetadata {
  'id' : string,
  'sku' : string,
  'stockQuantity' : bigint,
  'subcategory' : string,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'availability' : bigint,
  'pricePhpCents' : bigint,
  'category' : string,
  'images' : Array<ExternalBlob>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SocialLinks {
  'x' : string,
  'tiktok' : string,
  'instagram' : string,
  'email' : string,
  'facebook' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'dateCreated' : bigint,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFavorite' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductMetadata], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateProducts' : ActorMethod<
    [Array<string>, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGuestOrder' : ActorMethod<[Order, string], undefined>,
  'createGuestSession' : ActorMethod<[], string>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'createPasswordResetToken' : ActorMethod<[string, string, bigint], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAboutPageContent' : ActorMethod<[], string>,
  'getAllImages' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<ProductMetadata>>,
  'getAppearanceSettings' : ActorMethod<[], AppearanceSettings>,
  'getAvailableProductsByCategory' : ActorMethod<
    [string],
    Array<ProductMetadata>
  >,
  'getCallerFavorites' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFavorites' : ActorMethod<[Principal], Array<string>>,
  'getFeaturedProducts' : ActorMethod<[bigint], Array<ProductMetadata>>,
  'getGCashSettings' : ActorMethod<[], GCashSettings>,
  'getGuestOrder' : ActorMethod<[string, string], [] | [Order]>,
  'getImage' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getInventorySummary' : ActorMethod<[], Array<[string, bigint]>>,
  'getLowStockAlerts' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [ProductMetadata]>,
  'getProductImages' : ActorMethod<[string], [] | [Array<ExternalBlob>]>,
  'getProductsByCategory' : ActorMethod<[string], Array<ProductMetadata>>,
  'getProductsBySubcategory' : ActorMethod<[string], Array<ProductMetadata>>,
  'getSalesByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTopSellingProducts' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getTotalSales' : ActorMethod<[], bigint>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFavorite' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'removeFavorite' : ActorMethod<[string], undefined>,
  'resetAdminAccess' : ActorMethod<[], undefined>,
  'resetPasswordWithToken' : ActorMethod<[string, string], undefined>,
  'restockProduct' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppearanceSettings' : ActorMethod<[AppearanceSettings], undefined>,
  'updateGCashSettings' : ActorMethod<[GCashSettings], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductMetadata], undefined>,
  'updateProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'updateSocialLinks' : ActorMethod<[SocialLinks], undefined>,
  'updateStock' : ActorMethod<[string, bigint], undefined>,
  'uploadImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];