/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductMetadata = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'availability' : IDL.Nat,
  'pricePhpCents' : IDL.Nat,
  'category' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'returned' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'isGuestOrder' : IDL.Bool,
  'status' : OrderStatus,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Nat,
  'guestEmail' : IDL.Opt(IDL.Text),
  'shippingAddress' : IDL.Text,
  'totalPhpCents' : IDL.Nat,
  'items' : IDL.Vec(
    IDL.Record({
      'productId' : IDL.Text,
      'pricePhpCents' : IDL.Nat,
      'quantity' : IDL.Nat,
    })
  ),
});
export const AppearanceSettings = IDL.Record({
  'heroImage' : IDL.Opt(ExternalBlob),
  'shopBackground' : IDL.Opt(ExternalBlob),
  'homepageBackground' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'dateCreated' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const GCashSettings = IDL.Record({
  'merchantName' : IDL.Text,
  'qrCodeImage' : IDL.Opt(ExternalBlob),
  'accountNumber' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'x' : IDL.Text,
  'tiktok' : IDL.Text,
  'instagram' : IDL.Text,
  'email' : IDL.Text,
  'facebook' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductMetadata], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateProducts' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGuestOrder' : IDL.Func([Order, IDL.Text], [], []),
  'createGuestSession' : IDL.Func([], [IDL.Text], []),
  'createOrder' : IDL.Func([Order], [], []),
  'createPasswordResetToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAboutPageContent' : IDL.Func([], [IDL.Text], ['query']),
  'getAllImages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(ProductMetadata)], ['query']),
  'getAppearanceSettings' : IDL.Func([], [AppearanceSettings], ['query']),
  'getAvailableProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductMetadata)],
      ['query'],
    ),
  'getCallerFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductMetadata)],
      ['query'],
    ),
  'getGCashSettings' : IDL.Func([], [GCashSettings], ['query']),
  'getGuestOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], ['query']),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getInventorySummary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getLowStockAlerts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductMetadata)], ['query']),
  'getProductImages' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(ExternalBlob))],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductMetadata)],
      ['query'],
    ),
  'getProductsBySubcategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductMetadata)],
      ['query'],
    ),
  'getSalesByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTopSellingProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTotalSales' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'resetAdminAccess' : IDL.Func([], [], []),
  'resetPasswordWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'restockProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactForm' : IDL.Func([ContactSubmission], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppearanceSettings' : IDL.Func([AppearanceSettings], [], []),
  'updateGCashSettings' : IDL.Func([GCashSettings], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductMetadata], [], []),
  'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
  'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
  'updateStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductMetadata = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'availability' : IDL.Nat,
    'pricePhpCents' : IDL.Nat,
    'category' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'returned' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'isGuestOrder' : IDL.Bool,
    'status' : OrderStatus,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Nat,
    'guestEmail' : IDL.Opt(IDL.Text),
    'shippingAddress' : IDL.Text,
    'totalPhpCents' : IDL.Nat,
    'items' : IDL.Vec(
      IDL.Record({
        'productId' : IDL.Text,
        'pricePhpCents' : IDL.Nat,
        'quantity' : IDL.Nat,
      })
    ),
  });
  const AppearanceSettings = IDL.Record({
    'heroImage' : IDL.Opt(ExternalBlob),
    'shopBackground' : IDL.Opt(ExternalBlob),
    'homepageBackground' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'dateCreated' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const GCashSettings = IDL.Record({
    'merchantName' : IDL.Text,
    'qrCodeImage' : IDL.Opt(ExternalBlob),
    'accountNumber' : IDL.Text,
  });
  const SocialLinks = IDL.Record({
    'x' : IDL.Text,
    'tiktok' : IDL.Text,
    'instagram' : IDL.Text,
    'email' : IDL.Text,
    'facebook' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductMetadata], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateProducts' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGuestOrder' : IDL.Func([Order, IDL.Text], [], []),
    'createGuestSession' : IDL.Func([], [IDL.Text], []),
    'createOrder' : IDL.Func([Order], [], []),
    'createPasswordResetToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAboutPageContent' : IDL.Func([], [IDL.Text], ['query']),
    'getAllImages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(ProductMetadata)], ['query']),
    'getAppearanceSettings' : IDL.Func([], [AppearanceSettings], ['query']),
    'getAvailableProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductMetadata)],
        ['query'],
      ),
    'getCallerFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductMetadata)],
        ['query'],
      ),
    'getGCashSettings' : IDL.Func([], [GCashSettings], ['query']),
    'getGuestOrder' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Order)],
        ['query'],
      ),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getInventorySummary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getLowStockAlerts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(ProductMetadata)], ['query']),
    'getProductImages' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(ExternalBlob))],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductMetadata)],
        ['query'],
      ),
    'getProductsBySubcategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductMetadata)],
        ['query'],
      ),
    'getSalesByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTopSellingProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTotalSales' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'resetAdminAccess' : IDL.Func([], [], []),
    'resetPasswordWithToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'restockProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactForm' : IDL.Func([ContactSubmission], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppearanceSettings' : IDL.Func([AppearanceSettings], [], []),
    'updateGCashSettings' : IDL.Func([GCashSettings], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductMetadata], [], []),
    'updateProfilePicture' : IDL.Func([ExternalBlob], [], []),
    'updateSocialLinks' : IDL.Func([SocialLinks], [], []),
    'updateStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };