/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ProductMetadata {
    id: string;
    sku: string;
    stockQuantity: bigint;
    subcategory: string;
    name: string;
    tags: Array<string>;
    description: string;
    availability: bigint;
    pricePhpCents: bigint;
    category: string;
    images: Array<ExternalBlob>;
}
export interface SocialLinks {
    x: string;
    tiktok: string;
    instagram: string;
    email: string;
    facebook: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AppearanceSettings {
    heroImage?: ExternalBlob;
    shopBackground?: ExternalBlob;
    homepageBackground?: ExternalBlob;
}
export interface Order {
    id: string;
    isGuestOrder: boolean;
    status: OrderStatus;
    paymentMethod: string;
    userId?: Principal;
    createdAt: bigint;
    guestEmail?: string;
    shippingAddress: string;
    totalPhpCents: bigint;
    items: Array<{
        productId: string;
        pricePhpCents: bigint;
        quantity: bigint;
    }>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface GCashSettings {
    merchantName: string;
    qrCodeImage?: ExternalBlob;
    accountNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    principal: Principal;
    dateCreated: bigint;
    name: string;
    email: string;
    passwordHash: string;
    profilePicture?: ExternalBlob;
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered",
    returned = "returned"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addFavorite(productId: string): Promise<void>;
    addProduct(product: ProductMetadata): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateProducts(ids: Array<string>, price: bigint | null, stockQuantity: bigint | null): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGuestOrder(order: Order, guestSessionId: string): Promise<void>;
    createGuestSession(): Promise<string>;
    createOrder(order: Order): Promise<void>;
    createPasswordResetToken(email: string, token: string, expiresAt: bigint): Promise<void>;
    deleteProduct(productId: string): Promise<void>;
    getAboutPageContent(): Promise<string>;
    getAllImages(): Promise<Array<[string, ExternalBlob]>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<ProductMetadata>>;
    getAppearanceSettings(): Promise<AppearanceSettings>;
    getAvailableProductsByCategory(category: string): Promise<Array<ProductMetadata>>;
    getCallerFavorites(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getFavorites(user: Principal): Promise<Array<string>>;
    getFeaturedProducts(limit: bigint): Promise<Array<ProductMetadata>>;
    getGCashSettings(): Promise<GCashSettings>;
    getGuestOrder(orderId: string, guestSessionId: string): Promise<Order | null>;
    getImage(id: string): Promise<ExternalBlob | null>;
    getInventorySummary(): Promise<Array<[string, bigint]>>;
    getLowStockAlerts(threshold: bigint): Promise<Array<[string, bigint]>>;
    getOrder(orderId: string): Promise<Order | null>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    getProduct(productId: string): Promise<ProductMetadata | null>;
    getProductImages(productId: string): Promise<Array<ExternalBlob> | null>;
    getProductsByCategory(category: string): Promise<Array<ProductMetadata>>;
    getProductsBySubcategory(subcategory: string): Promise<Array<ProductMetadata>>;
    getSalesByCategory(): Promise<Array<[string, bigint]>>;
    getSocialLinks(): Promise<SocialLinks>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTopSellingProducts(limit: bigint): Promise<Array<[string, bigint]>>;
    getTotalSales(): Promise<bigint>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isAdminAssigned(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFavorite(productId: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    registerUser(name: string, email: string, passwordHash: string): Promise<void>;
    removeFavorite(productId: string): Promise<void>;
    resetAdminAccess(): Promise<void>;
    resetPasswordWithToken(token: string, newPasswordHash: string): Promise<void>;
    restockProduct(productId: string, quantity: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitContactForm(submission: ContactSubmission): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAppearanceSettings(settings: AppearanceSettings): Promise<void>;
    updateGCashSettings(settings: GCashSettings): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateProduct(product: ProductMetadata): Promise<void>;
    updateProfilePicture(picture: ExternalBlob): Promise<void>;
    updateSocialLinks(newLinks: SocialLinks): Promise<void>;
    updateStock(productId: string, quantity: bigint): Promise<void>;
    uploadImage(id: string, blob: ExternalBlob): Promise<void>;
}
import type { AppearanceSettings as _AppearanceSettings, ExternalBlob as _ExternalBlob, GCashSettings as _GCashSettings, Order as _Order, OrderStatus as _OrderStatus, ProductMetadata as _ProductMetadata, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_ProductMetadata_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_ProductMetadata_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateProducts(arg0: Array<string>, arg1: bigint | null, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateProducts(arg0, to_candid_opt_n14(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n14(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateProducts(arg0, to_candid_opt_n14(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n14(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGuestOrder(arg0: Order, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuestOrder(to_candid_Order_n15(this.uploadFile, this.downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuestOrder(to_candid_Order_n15(this.uploadFile, this.downloadFile, arg0), arg1);
            return result;
        }
    }
    async createGuestSession(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuestSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuestSession();
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_Order_n15(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_Order_n15(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async createPasswordResetToken(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPasswordResetToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPasswordResetToken(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAboutPageContent(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutPageContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutPageContent();
            return result;
        }
    }
    async getAllImages(): Promise<Array<[string, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImages();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImages();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<ProductMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppearanceSettings(): Promise<AppearanceSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppearanceSettings();
                return from_candid_AppearanceSettings_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppearanceSettings();
            return from_candid_AppearanceSettings_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAvailableProductsByCategory(arg0: string): Promise<Array<ProductMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableProductsByCategory(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableProductsByCategory(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerFavorites();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getFavorites(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites(arg0);
            return result;
        }
    }
    async getFeaturedProducts(arg0: bigint): Promise<Array<ProductMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGCashSettings(): Promise<GCashSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getGCashSettings();
                return from_candid_GCashSettings_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGCashSettings();
            return from_candid_GCashSettings_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGuestOrder(arg0: string, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestOrder(arg0, arg1);
                return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestOrder(arg0, arg1);
            return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getImage(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImage(arg0);
                return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImage(arg0);
            return from_candid_opt_n35(this.uploadFile, this.downloadFile, result);
        }
    }
    async getInventorySummary(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventorySummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventorySummary();
            return result;
        }
    }
    async getLowStockAlerts(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockAlerts(arg0);
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n17(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n17(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<ProductMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n44(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n44(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductImages(arg0: string): Promise<Array<ExternalBlob> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductImages(arg0);
                return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductImages(arg0);
            return from_candid_opt_n45(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<ProductMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductsBySubcategory(arg0: string): Promise<Array<ProductMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsBySubcategory(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsBySubcategory(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSalesByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByCategory();
            return result;
        }
    }
    async getSocialLinks(): Promise<SocialLinks> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialLinks();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTopSellingProducts(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopSellingProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopSellingProducts(arg0);
            return result;
        }
    }
    async getTotalSales(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSales();
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAdminAssigned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminAssigned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminAssigned();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFavorite(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFavorite(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async removeFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async resetAdminAccess(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminAccess();
            return result;
        }
    }
    async resetPasswordWithToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithToken(arg0, arg1);
            return result;
        }
    }
    async restockProduct(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restockProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restockProduct(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n49(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAppearanceSettings(arg0: AppearanceSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppearanceSettings(await to_candid_AppearanceSettings_n51(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppearanceSettings(await to_candid_AppearanceSettings_n51(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateGCashSettings(arg0: GCashSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGCashSettings(await to_candid_GCashSettings_n53(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGCashSettings(await to_candid_GCashSettings_n53(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n17(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n17(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: ProductMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_ProductMetadata_n8(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_ProductMetadata_n8(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateSocialLinks(arg0: SocialLinks): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocialLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocialLinks(arg0);
            return result;
        }
    }
    async updateStock(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1);
            return result;
        }
    }
    async uploadImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(arg0, await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(arg0, await to_candid_ExternalBlob_n11(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AppearanceSettings_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppearanceSettings): Promise<AppearanceSettings> {
    return await from_candid_record_n34(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_GCashSettings_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GCashSettings): Promise<GCashSettings> {
    return await from_candid_record_n42(uploadFile, downloadFile, value);
}
function from_candid_OrderStatus_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_Order_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
async function from_candid_ProductMetadata_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductMetadata): Promise<ProductMetadata> {
    return await from_candid_record_n31(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n38(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n37(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n23(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductMetadata]): Promise<ProductMetadata | null> {
    return value.length === 0 ? null : await from_candid_ProductMetadata_n30(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalBlob>]): Promise<Array<ExternalBlob> | null> {
    return value.length === 0 ? null : await from_candid_vec_n32(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isGuestOrder: boolean;
    status: _OrderStatus;
    paymentMethod: string;
    userId: [] | [Principal];
    createdAt: bigint;
    guestEmail: [] | [string];
    shippingAddress: string;
    totalPhpCents: bigint;
    items: Array<{
        productId: string;
        pricePhpCents: bigint;
        quantity: bigint;
    }>;
}): {
    id: string;
    isGuestOrder: boolean;
    status: OrderStatus;
    paymentMethod: string;
    userId?: Principal;
    createdAt: bigint;
    guestEmail?: string;
    shippingAddress: string;
    totalPhpCents: bigint;
    items: Array<{
        productId: string;
        pricePhpCents: bigint;
        quantity: bigint;
    }>;
} {
    return {
        id: value.id,
        isGuestOrder: value.isGuestOrder,
        status: from_candid_OrderStatus_n25(uploadFile, downloadFile, value.status),
        paymentMethod: value.paymentMethod,
        userId: record_opt_to_undefined(from_candid_opt_n27(uploadFile, downloadFile, value.userId)),
        createdAt: value.createdAt,
        guestEmail: record_opt_to_undefined(from_candid_opt_n28(uploadFile, downloadFile, value.guestEmail)),
        shippingAddress: value.shippingAddress,
        totalPhpCents: value.totalPhpCents,
        items: value.items
    };
}
async function from_candid_record_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    stockQuantity: bigint;
    subcategory: string;
    name: string;
    tags: Array<string>;
    description: string;
    availability: bigint;
    pricePhpCents: bigint;
    category: string;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    sku: string;
    stockQuantity: bigint;
    subcategory: string;
    name: string;
    tags: Array<string>;
    description: string;
    availability: bigint;
    pricePhpCents: bigint;
    category: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        sku: value.sku,
        stockQuantity: value.stockQuantity,
        subcategory: value.subcategory,
        name: value.name,
        tags: value.tags,
        description: value.description,
        availability: value.availability,
        pricePhpCents: value.pricePhpCents,
        category: value.category,
        images: await from_candid_vec_n32(uploadFile, downloadFile, value.images)
    };
}
async function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroImage: [] | [_ExternalBlob];
    shopBackground: [] | [_ExternalBlob];
    homepageBackground: [] | [_ExternalBlob];
}): Promise<{
    heroImage?: ExternalBlob;
    shopBackground?: ExternalBlob;
    homepageBackground?: ExternalBlob;
}> {
    return {
        heroImage: record_opt_to_undefined(await from_candid_opt_n35(uploadFile, downloadFile, value.heroImage)),
        shopBackground: record_opt_to_undefined(await from_candid_opt_n35(uploadFile, downloadFile, value.shopBackground)),
        homepageBackground: record_opt_to_undefined(await from_candid_opt_n35(uploadFile, downloadFile, value.homepageBackground))
    };
}
async function from_candid_record_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    dateCreated: bigint;
    name: string;
    email: string;
    passwordHash: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    principal: Principal;
    dateCreated: bigint;
    name: string;
    email: string;
    passwordHash: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        principal: value.principal,
        dateCreated: value.dateCreated,
        name: value.name,
        email: value.email,
        passwordHash: value.passwordHash,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n35(uploadFile, downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    merchantName: string;
    qrCodeImage: [] | [_ExternalBlob];
    accountNumber: string;
}): Promise<{
    merchantName: string;
    qrCodeImage?: ExternalBlob;
    accountNumber: string;
}> {
    return {
        merchantName: value.merchantName,
        qrCodeImage: record_opt_to_undefined(await from_candid_opt_n35(uploadFile, downloadFile, value.qrCodeImage)),
        accountNumber: value.accountNumber
    };
}
function from_candid_record_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n28(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n21(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    returned: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "returned" in value ? OrderStatus.returned : value;
}
function from_candid_variant_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n20(uploadFile, downloadFile, x)));
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n23(uploadFile, downloadFile, x));
}
async function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductMetadata>): Promise<Array<ProductMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProductMetadata_n30(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n21(uploadFile, downloadFile, x)));
}
async function to_candid_AppearanceSettings_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppearanceSettings): Promise<_AppearanceSettings> {
    return await to_candid_record_n52(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_GCashSettings_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GCashSettings): Promise<_GCashSettings> {
    return await to_candid_record_n54(uploadFile, downloadFile, value);
}
function to_candid_OrderStatus_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n18(uploadFile, downloadFile, value);
}
function to_candid_Order_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n16(uploadFile, downloadFile, value);
}
async function to_candid_ProductMetadata_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductMetadata): Promise<_ProductMetadata> {
    return await to_candid_record_n9(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n50(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isGuestOrder: boolean;
    status: OrderStatus;
    paymentMethod: string;
    userId?: Principal;
    createdAt: bigint;
    guestEmail?: string;
    shippingAddress: string;
    totalPhpCents: bigint;
    items: Array<{
        productId: string;
        pricePhpCents: bigint;
        quantity: bigint;
    }>;
}): {
    id: string;
    isGuestOrder: boolean;
    status: _OrderStatus;
    paymentMethod: string;
    userId: [] | [Principal];
    createdAt: bigint;
    guestEmail: [] | [string];
    shippingAddress: string;
    totalPhpCents: bigint;
    items: Array<{
        productId: string;
        pricePhpCents: bigint;
        quantity: bigint;
    }>;
} {
    return {
        id: value.id,
        isGuestOrder: value.isGuestOrder,
        status: to_candid_OrderStatus_n17(uploadFile, downloadFile, value.status),
        paymentMethod: value.paymentMethod,
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        createdAt: value.createdAt,
        guestEmail: value.guestEmail ? candid_some(value.guestEmail) : candid_none(),
        shippingAddress: value.shippingAddress,
        totalPhpCents: value.totalPhpCents,
        items: value.items
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    dateCreated: bigint;
    name: string;
    email: string;
    passwordHash: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    principal: Principal;
    dateCreated: bigint;
    name: string;
    email: string;
    passwordHash: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        principal: value.principal,
        dateCreated: value.dateCreated,
        name: value.name,
        email: value.email,
        passwordHash: value.passwordHash,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.profilePicture)) : candid_none()
    };
}
async function to_candid_record_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroImage?: ExternalBlob;
    shopBackground?: ExternalBlob;
    homepageBackground?: ExternalBlob;
}): Promise<{
    heroImage: [] | [_ExternalBlob];
    shopBackground: [] | [_ExternalBlob];
    homepageBackground: [] | [_ExternalBlob];
}> {
    return {
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.heroImage)) : candid_none(),
        shopBackground: value.shopBackground ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.shopBackground)) : candid_none(),
        homepageBackground: value.homepageBackground ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.homepageBackground)) : candid_none()
    };
}
async function to_candid_record_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    merchantName: string;
    qrCodeImage?: ExternalBlob;
    accountNumber: string;
}): Promise<{
    merchantName: string;
    qrCodeImage: [] | [_ExternalBlob];
    accountNumber: string;
}> {
    return {
        merchantName: value.merchantName,
        qrCodeImage: value.qrCodeImage ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.qrCodeImage)) : candid_none(),
        accountNumber: value.accountNumber
    };
}
async function to_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sku: string;
    stockQuantity: bigint;
    subcategory: string;
    name: string;
    tags: Array<string>;
    description: string;
    availability: bigint;
    pricePhpCents: bigint;
    category: string;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    sku: string;
    stockQuantity: bigint;
    subcategory: string;
    name: string;
    tags: Array<string>;
    description: string;
    availability: bigint;
    pricePhpCents: bigint;
    category: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        sku: value.sku,
        stockQuantity: value.stockQuantity,
        subcategory: value.subcategory,
        name: value.name,
        tags: value.tags,
        description: value.description,
        availability: value.availability,
        pricePhpCents: value.pricePhpCents,
        category: value.category,
        images: await to_candid_vec_n10(uploadFile, downloadFile, value.images)
    };
}
function to_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    returned: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.returned ? {
        returned: null
    } : value;
}
async function to_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
